- hosts: dev
  gather_facts: false
  become: true
  vars:
    app_dir: /opt/app
    repo_url: https://github.com/Krynclv/aws-exo5.git
    branch: main
  tasks:
    - raw: apk update && apk add --no-cache python3 git nodejs npm nginx curl
    - setup:
    - file:
        path: "{{ app_dir }}"
        state: directory
        mode: "0755"
    - git:
        repo: "{{ repo_url }}"
        dest: "{{ app_dir }}"
        version: "{{ branch }}"
        force: yes
    - shell: |
        cd "{{ app_dir }}"
        if [ -f package.json ]; then
          npm ci || npm install
          npm run build || true
        fi
      args: { executable: /bin/sh }
    - file:
        path: /usr/share/nginx/html
        state: directory
        mode: "0755"
    - file:
        src: /usr/share/nginx/html
        dest: /var/www/html
        state: link
        force: true
    - copy:
        dest: /usr/share/nginx/html/index.html
        mode: "0644"
        content: |
          <!doctype html>
          <html lang="fr"><meta charset="utf-8"><title>Dev OK</title>
          <h1>Déploiement DEV réussi</h1>
          <p>Host: {{ inventory_hostname }}</p>
          <p>Date: {{ ansible_date_time.iso8601 }}</p>
          </html>
    - lineinfile:
        path: /var/log/deploy.log
        create: true
        line: "{{ ansible_date_time.iso8601 }} - DEV deploy OK on {{ inventory_hostname }}"
    - shell: |
        nginx -t
        pgrep nginx >/dev/null && nginx -s reload || nginx
      args: { executable: /bin/sh }